remote_theme: jameshamann/jekyll-material-theme

url: https://snvmk.tk
baseurl: /cube-side-bot

title: CubeSide
description: Крутой Minecraft-сервер и Discord-сервер с ботом!
author: SNVMK и COCICKA
name: SNVMK и COCICKA
email: sidzahroman@gmail.com

parallax_image_one: /assets/background-header.jpg
parallax_image_two: /assets/background-header.jpg

display_footer: inital

portfolio_heading: Проекты
portfolio_type: carousel

project_one: "Сервер CubeSide"
project_one_description: Крутой Minecraft сервер
project_one_url: https://cubeside.online
project_one_icon: videogame_asset

project_button: Ссылка
github: https://github.com/SNVMK

permalink: /:title